### ISSUE TITLE
My games no longer display

### ISSUE THREAD

**Issue by Galbio** [GPUCode/citra#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1841

### Description of Issue

When I launch a game, the game isn't displayed on screen.
The sound effects and control works without any issue.

It was working with 1840 and stopped working at 1841

https://user-images.githubusercontent.com/101997612/219857407-5a1d0738-c6aa-441c-9428-8e70290c2631.mp4

(The video is Nightly 1844 but after testing it stopped at 1841)

### Expected Behavior

I can't really say anything

### Reproduction Steps

uhh... I click on a game

### Log File

[citra_log.txt](https://github.com/GPUCode/citra/files/10773989/citra_log.txt)

### System Configuration

CPU: Intel(R) Celeron(R) N4120 CPU @ 1.10GHz
GPU/Driver: Intel(R) UHD Graphics 600
RAM: 4GB
OS: Windows 11

**Comment by GPUCode** [comment]
You should post issues regarding Canary/Nightly in the main citra repo, this is strictly for vulkan related issues
