### ISSUE TITLE
Vulkan builds release schedule?

### ISSUE THREAD

**Issue by AlexS2412** [GPUCode/citra#31]
### Issue

How do you plan on releasing new builds for the experimental vulkan render?  sorry if this is too random.

**Comment by GPUCode** [comment]
It has been decided to split in the massive Vulkan PR into smaller ones to get it merged into official citra faster and with less bugs. The [first](https://github.com/citra-emu/citra/pull/6347) part was merged recently. The [second](https://github.com/citra-emu/citra/pull/6375) part is currently in canary. Most likely there will be a third part too for some finishing touches and the fourth one will just be the vulkan code dump.

**Comment by AlexS2412** [comment]
sadly newest vulkan build completely crashes on a black screen when a game is loaded, same load regressions because of SAF. very good progress though! glad to see it finally coming to fruition!
