### ISSUE TITLE
Custom GPU Driver not worlk with libadrenotools

### ISSUE THREAD

**Issue by innovation2013** [GPUCode/citra#37]
### Issue

I tried to use libadrenotools to load a custom driver, but all drivers except the default one caused crashes. Occasionally, one driver might display the game screen, but it also faced the same crashing issue after a few seconds.The same driver works well on Yuzu and Dolphin

**Comment by GPUCode** [comment]
Are you sure you used adrenotools? Citra does not yet support it, so the only way to test drivers is to sideload them with Magisk

**Comment by innovation2013** [comment]
Yes, I know that Citra does not support it currently. I tried to add support for adrenotools myself (like yuzu) and built it. For now, only the default system drivers can run properly. Other drivers, as mentioned above, either crash after running for a while or just black screen and crash immediately.

**Comment by GPUCode** [comment]
In that case I would recommend uploading the code to github to verify it's correctly loading the library

**Comment by innovation2013** [comment]
@GPUCode [https://github.com/GPUCode/citra/pull/38](url)  Now, I have uploaded the code about custom GPU driver. Could you please take a look at it? Thank you.
