### ISSUE TITLE
Fire Emblem Awakening SPIR-V issues

### ISSUE THREAD

**Issue by NineKain** [GPUCode/citra#4]
Small collection of issues I saw during my short testing

![image](https://user-images.githubusercontent.com/72826232/201484105-c3d5200d-818b-4523-a1cf-f6222243900a.png)
Blocky trees

![image](https://user-images.githubusercontent.com/72826232/201484123-7a69905b-deed-4cbd-ab3f-34b241fbb81a.png)
Blocky trees in battlefield

![image](https://user-images.githubusercontent.com/72826232/201484144-3dfb7644-1b23-4bfa-983b-507856e6d44f.png)
Very broken battles in general

**Comment by GPUCode** [comment]
@NineKain Pushed a commit that should fix this https://github.com/GPUCode/citra/commit/facddbfc8c098dbde47f12b5dce776a853205086 Can you retest with this?

**Comment by NineKain** [comment]
All fixed, thank you
