### ISSUE TITLE
A Link Between Worlds Crashes Consistently (Steam Deck)

### ISSUE THREAD

**Issue by rawdatafeel** [GPUCode/citra#6]
- You have provided the version (commit hash) of Citra you are using: vulkan-2-0b4731b (2022-11-20)
- You have provided sufficient detail for the issue to be reproduced: `A Link Between Worlds` consistently crashes on Steam Deck, looks like it's related to pipeline caching. 
- You have provided system specs (if relevant): Steam Deck, Specific Specs: https://store.steampowered.com/steamdeck
- Please also provide:
  - For any issues, a log file: https://gist.github.com/rawdatafeel/821aa7812e3bcaca31dd915795f3f580
  - For graphical issues, comparison screenshots with real hardware: N/A
  - For emulation inaccuracies, a test-case (if able): N/A

**Comment by GPUCode** [comment]
Please turn on debug renderer and upload a new log. The game will be slower but it will reveal more information about what error is occuring

**Comment by rawdatafeel** [comment]
Here you go! https://gist.github.com/rawdatafeel/d6459394c446d0daf0ad51240022b3f3

**Comment by rawdatafeel** [comment]
Testing a few additional games, with debug render on:

1. A Link Between Worlds: https://gist.github.com/rawdatafeel/6ad9d802e1b6447ed404b91583930c0b
2. Super Mario 3D Land: https://gist.github.com/rawdatafeel/6ad9d802e1b6447ed404b91583930c0b
3.  Ocarina of Time: https://gist.github.com/rawdatafeel/6acba738a6385d9a5a41aff6183e81c0
4. Senran Kagura 2: https://gist.github.com/rawdatafeel/62bd8d175a09b319bbf854c2eb2d069a

**Comment by GPUCode** [comment]
Fixed by 0e987959a6a2e7d87a5c0704a51796fe95da4174
