### ISSUE TITLE
moltenvk gives a permission error

### ISSUE THREAD

**Issue by MichaelGDev48** [GPUCode/citra#7]
I downloaded the artifact file from the ci build for macos
when I try to fix the "this app is broken or damaged" error i get this
Permission denied: '/Applications/citra-qt-vulkan.app/Contents/lib/libMoltenVK.dylib'
I also get this same issue when i self build this

**Comment by GPUCode** [comment]
Uh macos isn't my area of expertise, the patches to make it work there were submitted by @Steveice10 they might be able to help more in this case

**Comment by Steveice10** [comment]
I'm unable to reproduce, what version of macOS is this? I'm on macOS 13 so there may be differences.

When I download and extract the app, I just have to go into the security settings, allow running the app, and it works fine.

**Comment by MichaelGDev48** [comment]
> I'm unable to reproduce, what version of macOS is this? I'm on macOS 13 so there may be differences.
> 
> When I download and extract the app, I just have to go into the security settings, allow running the app, and it works fine.

yeah its not showing in security since im getting "may be damaged or incomplete" 
im on mac os ventura

**Comment by MichaelGDev48** [comment]
oh apparently this is caused by renaming the app (bc i wanted to have both a nightly build and this vulkan build)

**Comment by Steveice10** [comment]
Yeah that might be the cause of the damaged issue. What might fix your attempt to clear the attributes and fix it is ```chmod +w citra-qt.app/Contents/lib/libMoltenVK.dylib``` if you still want to try that.
